// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllWeapons():Promise<main.ResponseWeaponArray>;

export function GetWeaponTree(arg1:number):Promise<main.ResponseWeaponTree>;

export function GetWeaponsByQuery(arg1:main.RequestQuery):Promise<main.ResponseWeaponArray>;
