// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllWeapons():Promise<Array<main.Weapon>>;

export function GetWeaponByID(arg1:number):Promise<main.Weapon>;

export function GetWeaponsByName(arg1:string):Promise<Array<main.Weapon>>;
