// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllWeapons():Promise<main.PayloadWeaponArray>;

export function GetWeaponsByQuery(arg1:string):Promise<main.PayloadWeaponArray>;
