// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllWeapons() {
  return window['go']['main']['App']['GetAllWeapons']();
}

export function GetWeaponsByQuery(arg1) {
  return window['go']['main']['App']['GetWeaponsByQuery'](arg1);
}
